# Base configs
baseurl: "https://eeerinnern.github.io/photography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Yiping Chen"
subtitle: "See the world through my eyes!"
author: "Yiping Chen"
header:
 title: "Photography"
 subtitle: "by Yiping Chen"
footer:
 name: "Hey there, my name is Yiping"
 bio: "I am a master student of Economics and have strong interest in capturing the lovely moments of the world."
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/eeerin688/"
  linkedin: "https://www.linkedin.com/in/yiping-chen-163002225/"
  github: "https://github.com/EEErinnern"
